### PR TITLE
UI enhancement

### PR DESCRIPTION
**Pull request by partik03**
This Pull request is for the issue #43  by author @partik03

### CODE REVIEW

**Comment by Rick-mad-lab** [comment]
Add your screenshorts

**Comment by partik03** [comment]
Screenshot from 2022-10-02 12-15-54

This is how it looks like now
Also I have added box shadow around the input bar which gives a beautiful effect when in focus

**Comment by partik03** [comment]
@Rick-mad-lab kindly review my pr

**Comment by Rick-mad-lab** [comment]
not up to the mark

**Pull request closed without merging**
