### PR TITLE
Created footer

### PR DESCRIPTION
**Pull request by Vanshiii203**
issue #106

https://user-images.githubusercontent.com/94471189/198519807-78a15390-a7da-4e5b-a213-167791c35cb9.mp4

### CODE REVIEW

**Comment by Vanshiii203** [comment]
@Rick-mad-lab  please review and merge this

**Comment by Rick-mad-lab** [comment]
@Vanshiii203 nice 👍

**Comment by Rick-mad-lab** [comment]
Make this footer transparent

**Comment by Rick-mad-lab** [comment]
I am not reverting your contribution

**Comment by Vanshiii203** [comment]
> I am not reverting your contribution

So should I raise another pr where I make the footer transparent

**Pull request merged**
