### PR TITLE
feat(voice-input): add voice handling for user

### PR DESCRIPTION
**Pull request by aanchal-fatwani**
### Related Issue or bug
Add voice input handling for users

Fixes: https://github.com/Rick-mad-lab/Todolist/issues/8

### Proposed Changes

- Added microphone icon to allow the user to enter input by speaking
- Added handling to listen to user and prefill in input box for adding as todo

### CODE REVIEW

**Comment by Rick-mad-lab** [comment]
Nice feature but can you please raise another PR to the [Ideas](https://github.com/Rick-mad-lab/Todolist/tree/Ideas) branch I don't want a new element into prod. without testing.

**Comment by Rick-mad-lab** [comment]
AND ALSO RESOLVE THE CONFLICTS

**Comment by aanchal-fatwani** [comment]
@Rick-mad-lab I've incorporated suggestions. Please check again if the changes are okay to be accepted.
Thanks

**Comment by Rick-mad-lab** [comment]
Okie let's see

**Pull request merged**
