### PR TITLE
Instruction button and styling

### PR DESCRIPTION
**Pull request by Gunjanrathore8178**
1) Changed the background
2)added an instruction button
3)added an instruction page
4) added a footer to the instruction page.

### CODE REVIEW

**Comment by Rick-mad-lab** [comment]
add after changes SS.

**Comment by Gunjanrathore8178** [comment]
Ok

**Comment by Gunjanrathore8178** [comment]
<h2><b>First page when we go live</b></h2>
one

<h2><b>When we change the theme the background image changes</b></h2> 
second
3e-4d34-955c-bf5490948094.png)

**Comment by Gunjanrathore8178** [comment]
### This is the first background image
one

### This is the second theme background image
second

### This is the Instruction page
third

**Comment by Gunjanrathore8178** [comment]
I had attached the SS
 Kindly view them

**Comment by Gunjanrathore8178** [comment]
@Rick-mad-lab is there anything missing which I should work on?

**Comment by Rick-mad-lab** [comment]
too much fancy not good !

**Pull request closed without merging**
