### PR TITLE
Customized the dark mode button

### PR DESCRIPTION
**Pull request by zugzwang03**
resolved issue #98 

Screenshots:

https://user-images.githubusercontent.com/95460021/197372042-8d60dc94-2f98-470a-981e-bb3c34feaaca.mp4

### CODE REVIEW

**Comment by zugzwang03** [comment]
@Rick-mad-lab

**Comment by zugzwang03** [comment]
@Rick-mad-lab

**Comment by Rick-mad-lab** [comment]
> nice update definitely a great design choice.

**Review by Rick-mad-lab — APPROVED** [review]

**Comment by zugzwang03** [comment]
> > nice update definitely a great design choice.

Thanks 😊

**Pull request merged**
