### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by Darkrider0007**
The previous background is not quite good for users. I make a slight change in the background.

### CODE REVIEW

**Comment by Rick-mad-lab** [comment]
Share Screenshots of updates

**Comment by Darkrider0007** [comment]
Screenshot (5)

**Comment by Rick-mad-lab** [comment]
nice but add dark and light theme fork sync and update your UI nice

**Comment by Rick-mad-lab** [comment]
don't raise PR to master to master

**Comment by Darkrider0007** [comment]
Screenshot 2022-10-03 131456

**Pull request closed without merging**
